# Importar librerias necesarias

conda install ipykernel

In [1]:
import pandas as pd
import os
import zipfile
import glob
import dask

# Paths

Ruta actual

In [2]:
ruta_actual = os.path.abspath(os.curdir)
print(ruta_actual)

C:\Users\Admin\Documents\Github\Geohashes-Colegios\Codes\Python\Lectura de geohashes

Ruta de carpetas

In [3]:
#path_personal = r"C:\Users\BS\Documents\Github"
path_personal = r"C:\Users\Admin\Documents\Github"

path_global = path_personal + r"\Geohashes-Colegios"

path_data = path_global + r"\Data"

path_data_geohashes = path_data + r"\Geohashes"

print(path_personal)
print(path_global)
print(path_data)
print(path_data_geohashes)

C:\Users\Admin\Documents\Github
C:\Users\Admin\Documents\Github\Geohashes-Colegios
C:\Users\Admin\Documents\Github\Geohashes-Colegios\Data
C:\Users\Admin\Documents\Github\Geohashes-Colegios\Data\Geohashes

Cambiando ruta

In [4]:
os.chdir(path_data_geohashes)

In [5]:
ruta_actual = os.path.abspath(os.curdir)
print(ruta_actual)

C:\Users\Admin\Documents\Github\Geohashes-Colegios\Data\Geohashes

Lectura de archivos

In [6]:
files = os.listdir()
files

['Argentina.zip',
 'Bolivia.zip',
 'Brasil.zip',
 'Chile.zip',
 'Colombia.zip',
 'Dominicana.zip',
 'Ecuador.zip',
 'Guatemala.zip',
 'Honduras.zip',
 'Mexico.zip',
 'Nicaragua.zip',
 'Paraguay.zip',
 'Peru.zip',
 'Uruguay.zip',
 'Venezuela.zip']

# Paises peque√±os

In [7]:
nompaises = ['Bolivia','Chile','Colombia','Dominicana', 'Ecuador', 'Guatemala',
             'Honduras','Nicaragua','Paraguay','Peru','Uruguay','Venezuela']
len(nompaises)

12

In [8]:
df = pd.read_csv('Chile.zip')
_, l = dask.compute(df, df.size)
print("Numeros de registros", l/ len(df.columns))
df.head(10)

Numeros de registros 19166083.0

,Unnamed: 0,geohash,g_adm_1,g_adm_3,month,day,n_visitantes_geohash,n_visitantes_adm3,n_visitantes_0,n_visitantes_1,...,n_visitantes_14,n_visitantes_15,n_visitantes_16,n_visitantes_17,n_visitantes_18,n_visitantes_19,n_visitantes_20,n_visitantes_21,n_visitantes_22,n_visitantes_23
0,0,66jt91k,5.0,5702.0,5,3,4,2,0,0,...,1,1,0,1,0,0,0,1,0,0
1,1,63knfd2,8.0,8107.0,3,16,15,11,1,0,...,3,4,1,1,2,2,0,1,1,0
2,2,637uz4p,8.0,8106.0,3,16,3,3,0,0,...,0,0,0,0,0,1,0,0,0,0
3,3,66jec5e,13.0,13303.0,5,6,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,4,66jcejx,13.0,13113.0,3,10,5,4,0,0,...,0,1,1,0,0,0,0,0,0,0
5,5,63kn8s1,8.0,8112.0,6,19,8,5,0,0,...,0,0,1,0,0,1,1,0,0,0
6,6,66j9rw0,13.0,13121.0,3,15,4,3,0,0,...,0,1,0,0,0,0,0,0,0,0
7,7,66j0dx9,5.0,5601.0,4,3,3,0,0,0,...,0,1,0,0,0,1,0,0,0,0
8,8,63hqrz2,9.0,9211.0,6,1,1,1,0,0,...,0,0,0,0,0,1,0,0,0,0
9,9,66jbf5g,13.0,13201.0,6,13,4,2,1,0,...,1,0,0,0,0,1,0,0,0,0

In [9]:
del df

In [10]:
df = pd.read_csv('Peru.zip')
_, l = dask.compute(df, df.size)
print("Numeros de registros", l/ len(df.columns))
df.head(10)

Numeros de registros 13536433.0

,Unnamed: 0,geohash,g_adm_1,g_adm_2,g_adm_3,month,day,n_visitantes_geohash,n_visitantes_adm3,n_visitantes_0,...,n_visitantes_14,n_visitantes_15,n_visitantes_16,n_visitantes_17,n_visitantes_18,n_visitantes_19,n_visitantes_20,n_visitantes_21,n_visitantes_22,n_visitantes_23
0,0,6mc7d2b,15,1501,150103,4,18,2,0,0,...,0,2,0,0,0,1,0,0,0,0
1,1,6mf7ym9,12,1202,120213,3,8,1,1,0,...,0,0,0,0,0,0,0,0,1,0
2,2,6myb2gp,17,1701,170101,5,9,2,0,0,...,0,0,0,0,0,0,0,0,0,0
3,3,6mj420y,4,401,40124,5,11,1,1,0,...,0,0,0,0,0,0,0,0,0,0
4,4,6q3gnyd,10,1006,100601,4,15,1,0,0,...,1,1,0,0,1,0,1,1,0,0
5,5,6mc7ut8,15,1501,150118,3,12,1,0,0,...,0,0,0,1,0,0,0,0,0,0
6,6,6q1z2vn,10,1001,100102,6,16,1,1,0,...,0,0,0,0,0,0,0,0,0,0
7,7,6mchwcw,15,1501,150106,3,30,1,0,0,...,0,0,0,0,0,0,0,1,0,0
8,8,6mc727p,15,1501,150114,5,21,34,31,1,...,3,2,4,4,0,0,0,0,0,0
9,9,6pqe5bc,24,2402,240201,6,6,1,1,0,...,0,0,0,0,0,0,0,0,0,0

In [11]:
del df